port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
ipv6: false
external-controller: '0.0.0.0:9090'

profile:
  store-selected: false
  tracing: true

proxies:

proxy-groups:
  # relay chains the proxies. proxies shall not contain a relay. No UDP support.
  # Traffic: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet
  -
    name: ğŸ”°å›½å¤–æµé‡
    type: select
    proxies:
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
      - AIRPORT
      - ğŸš€ç›´æ¥è¿æ¥
  -
    name: âš“ï¸å…¶ä»–æµé‡
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - ğŸš€ç›´æ¥è¿æ¥
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: âœˆï¸Telegram
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ™Discord
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ“˜Facebook
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬Youtube
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬Netflix
    type: select
    use:
      - airport-hk
      - airport-tw
      - airport-sg
      - airport-jp
      - airport-korea
      - airport-us
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬DisneyPlus
    type: select
    use:
      - airport-hk
      - airport-tw
      - airport-sg
      - airport-jp
      - airport-korea
      - airport-us
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬Hulu
    type: select
    use:
      - airport-hk
      - airport-tw
      - airport-sg
      - airport-jp
      - airport-korea
      - airport-us
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬HBO
    type: select
    use:
      - airport-hk
      - airport-tw
      - airport-sg
      - airport-jp
      - airport-korea
      - airport-us
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬å“”å“©å“”å“©
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ¬å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ§Spotify
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - ğŸš€ç›´æ¥è¿æ¥
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ®Steam
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ’»Microsoft
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ§§Paypal
    type: select
    proxies:
      - ğŸ”°å›½å¤–æµé‡
      - ğŸš€ç›´æ¥è¿æ¥
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸššAmazon
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸ“¡Speedtest
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸè‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸš€ç›´æ¥è¿æ¥
      - ğŸ”°å›½å¤–æµé‡
      - AIRPORT
      - AIRPORT-HK
      - AIRPORT-TW
      - AIRPORT-SG
      - AIRPORT-JP
      - AIRPORT-Korea
      - AIRPORT-US
      - AIRPORT-India
      - AIRPORT-EN
      - AIRPORT-Ireland
      - AIRPORT-RU
      - AIRPORT-Canada
      - AIRPORT-FR
      - AIRPORT-AU
  -
    name: ğŸš€ç›´æ¥è¿æ¥
    type: select
    proxies:
      - DIRECT
  -
    name: AIRPORT
    type: select
    use:
      - airport
  -
    name: AIRPORT-HK
    type: select
    use:
      - airport-hk
  -
    name: AIRPORT-TW
    type: select
    use:
      - airport-tw
  -
    name: AIRPORT-SG
    type: select
    use:
      - airport-sg
  -
    name: AIRPORT-JP
    type: select
    use:
      - airport-jp
  -
    name: AIRPORT-Korea
    type: select
    use:
      - airport-korea
  -
    name: AIRPORT-US
    type: select
    use:
      - airport-us  
  -
    name: AIRPORT-India
    type: select
    use:
      - airport-india 
  -
    name: AIRPORT-EN
    type: select
    use:
      - airport-en 
  -
    name: AIRPORT-Ireland
    type: select
    use:
      - airport-ireland 
  -
    name: AIRPORT-RU
    type: select
    use:
      - airport-ru
  -
    name: AIRPORT-Canada
    type: select
    use:
      - airport-canada
  -
    name: AIRPORT-FR
    type: select
    use:
      - airport-fr
  -
    name: AIRPORT-AU
    type: select
    use:
      - airport-au

proxy-providers:
  airport:
    type: http
    url: "" # è¿™é‡Œå¡«å…¥æœºåœºé“¾æ¥
    interval: 36000
    path: myprovider/proxies/provider-airport.yml
    health-check:
      enable: true
      interval: 36000
      # lazy: true
      url: http://www.gstatic.com/generate_204
  airport-hk:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'æ¸¯'
  airport-tw:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'å°æ¹¾'
  airport-sg:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'æ–°åŠ å¡'
  airport-jp:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'æ—¥æœ¬'
  airport-fr:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'æ³•å›½'
  airport-au:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'æ¾³å¤§åˆ©äºš'
  airport-ireland:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'çˆ±å°”å…°'
  airport-en:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'è‹±å›½'
  airport-korea:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'éŸ©å›½'
  airport-ru:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'ä¿„ç½—æ–¯'
  airport-us:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'ç¾å›½'
  airport-canada:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'åŠ æ‹¿å¤§'
  airport-india:
    type: file
    path: myprovider/proxies/provider-airport.yml
    filter: 'å°åº¦'

rules:
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-KEYWORD,aria2,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,Process,DIRECT
  - RULE-SET,AdBlock,REJECT
  - RULE-SET,Apple,ğŸè‹¹æœæœåŠ¡
  - RULE-SET,Adobe,âš“ï¸å…¶ä»–æµé‡
  - RULE-SET,Amazon,ğŸššAmazon
  - RULE-SET,BiliBili,ğŸ¬å“”å“©å“”å“©
  - RULE-SET,Facebook,ğŸ“˜Facebook 
  - RULE-SET,GitHub,ğŸ”°å›½å¤–æµé‡
  - RULE-SET,Google,ğŸ”°å›½å¤–æµé‡
  - RULE-SET,Microsoft,ğŸ’»Microsoft
  - RULE-SET,Netflix,ğŸ¬Netflix 
  - RULE-SET,DisneyPlus,ğŸ¬DisneyPlus 
  - RULE-SET,Hulu,ğŸ¬Hulu
  - RULE-SET,HBO,ğŸ¬HBO
  - RULE-SET,Speedtest,ğŸ“¡Speedtest
  - RULE-SET,Steam,ğŸ®Steam
  - RULE-SET,Spotify,ğŸ§Spotify
  - RULE-SET,Telegram,âœˆï¸Telegram 
  - RULE-SET,Twitter,ğŸ”°å›½å¤–æµé‡ 
  - RULE-SET,Tencent,ğŸš€ç›´æ¥è¿æ¥
  - RULE-SET,YouTube,ğŸ¬Youtube 
  - RULE-SET,PayPal,ğŸ§§Paypal
  - RULE-SET,Discord,ğŸ™Discord
  - RULE-SET,Proxy,ğŸ”°å›½å¤–æµé‡
  - DOMAIN-SUFFIX,live.cn,ğŸš€ç›´æ¥è¿æ¥

  - GEOIP,CN,DIRECT
  - MATCH,âš“ï¸å…¶ä»–æµé‡

rule-providers:
  AdBlock: 
    type: http
    behavior: classical
    path: myprovider/ruleset/AdBlock.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/AdBlock.yaml
    interval: 3600
  Apple: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Apple.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Apple.yaml
    interval: 3600
  Adobe: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Adobe.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Adobe.yaml
    interval: 3600
  Amazon: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Amazon.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Amazon.yaml
    interval: 3600
  China: 
    type: http
    behavior: classical
    path: myprovider/ruleset/China.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/China.yaml
    interval: 3600
  BiliBili: 
    type: http
    behavior: classical
    path: myprovider/ruleset/BiliBili.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Bilibili.yaml
    interval: 3600
  Facebook: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Facebook.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Facebook.yaml
    interval: 3600
  GitHub: 
    type: http
    behavior: classical
    path: myprovider/ruleset/GitHub.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/GitHub.yaml
    interval: 3600
  Google: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Google.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Google.yaml
    interval: 3600
  Microsoft: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Microsoft.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Microsoft.yaml
    interval: 3600
  Netflix: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Netflix.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Netflix.yaml
    interval: 3600
  Spotify: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Spotify.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Spotify.yaml
    interval: 3600
  Speedtest: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Speedtest.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Speedtest.yaml
    interval: 3600
  Steam: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Steam.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Steam.yaml
    interval: 3600
  Telegram: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Telegram.yaml
    interval: 3600
  Twitter: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Twitter.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Twitter.yaml
    interval: 3600
  Tencent: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Tencent.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Tencent.yaml
    interval: 3600
  YouTube: 
    type: http
    behavior: classical
    path: myprovider/ruleset/YouTube.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/YouTube.yaml
    interval: 3600
  PayPal: 
    type: http
    behavior: classical
    path: myprovider/ruleset/PayPal.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/PayPal.yaml
    interval: 3600
  Discord: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Discord.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Discord.yaml
    interval: 3600
  Proxy: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Proxy.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Proxy.yaml
    interval: 3600
  Process: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Process.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/ProcessFilter.yaml
    interval: 3600
  DisneyPlus: 
    type: http
    behavior: classical
    path: myprovider/ruleset/DisneyPlus.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/DisneyPlus.yaml
    interval: 3600
  Hulu: 
    type: http
    behavior: classical
    path: myprovider/ruleset/Hulu.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/Hulu.yaml
    interval: 3600
  HBO: 
    type: http
    behavior: classical
    path: myprovider/ruleset/HBO.yaml
    url: https://cdn.jsdelivr.net/gh/yeehonglee/Clash-Template-Config@master/Filter/HBO.yaml
    interval: 3600
